### ISSUE TITLE
GPIO.add_event_detect not working

### ISSUE THREAD

**Issue by SirIcy** [auto3000/RPi.GPIO_NP#1]
I have installed following standard image on my NanoPi Neo 1.2
http://www.mediafire.com/file/g4wwv8u4gl94t4l/nanopi-neo_ubuntu-core-xenial_4.11.2_20170705.img.zip

Output and GPIO.input are ok. But neither GPIO.add_event_detect nor GPIO.wait_for_edge is working. No event is triggered by any input.

**Comment by auto3000** [comment]
Hello, the ubuntu-core installation does not use this code repository (for sure). Maybe friendlyarm could give a support for their delivery.

This repo is only used for an early experiment with Yocto and I don't plan to use ubuntu-core in the short term sorry. Anyway, you may want to build this repo on ubuntu-core and you would check if you can reproduce the issue, this could be a good info.

**Comment by SirIcy** [comment]
Hi auto3000,
thanks for your answer. A python lib to access GPIO is the core functionality for me. I would like to use your solution. What is the best way for installation? Do you have an install guide? Shall I use a Debian image as basis?
Best regards,
SirIcy

**Comment by auto3000** [comment]
I see. This repo is only a direct integration of friendlyarm patches against RPi.GPIO. I did a short test this morning and I was unable to use the RPi.GPIO_NP library too. From a code review, I'm sure this code is not a valid port to the allwinner h3 SOC, some support is missing. I would dig further.

**Comment by auto3000** [comment]
Hello Sirlcy, I did push some patches on master branch yesterday. The GPIO.add_event_detect is working correctly. I tested a couple of other procedures GPIO.input GPIO.output GPIO.setup. Please note all my tests are done after a call to GPIO.setmode(GPIO.BOARD). 

Note: I did my tests on Yocto distribution. You may have to install this on your ubuntu installation. Regards.

**Comment by SirIcy** [comment]
Hi auto3000,
thx for your feedback. Meanwhile I have implemented OPI.GPIO from Orange Pi with some adaptions. This works good so far...

**Comment by martinopi444** [comment]
i'm trying to use wiringpi and  opi.GPIO in python to use function wiringPiISR   or add_event_detect for do a callback with a GPIO pin but it make a callback without any change in the pins.
With wiringpi I tried with the example callback.py and it was printing GPIO_CALLBACK  continuously without any change in the pins.
someone fixed it?
