### ISSUE TITLE
It doesn't work on NEO plus2

### ISSUE THREAD

**Issue by zhou-xuelin** [auto3000/RPi.GPIO_NP#7]
After installation  by  'python setup.py install' and using 'import RPi.GPIO' , it threw an error.

`
>>> import RPi.GPIO
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/RPi.GPIO_NP/RPi/GPIO/__init__.py", line 23, in <module>
    from RPi._GPIO import *
ModuleNotFoundError: No module named 'RPi._GPIO'

>>>import RPi._GPIO
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'RPi._GPIO'
`

**Comment by auto3000** [comment]
/root/RPi.GPIO_NP .... is an unusual installation path... this should be in /usr/.... Please reinstall this software and try to import the library from outside the RPi source directory.

**Comment by zhou-xuelin** [comment]
I have tried to install twice. Unfortunately, it still can't work on neither Python3 nor Python2. 
In addition, the OS environment is Armbian (Debian Buster). Does this problem have relation with OS or Drivers?

root@nanopineoplus2:/usr# git clone https://github.com/auto3000/RPi.GPIO_NP
Cloning into 'RPi.GPIO_NP'...
remote: Enumerating objects: 959, done.
remote: Total 959 (delta 0), reused 0 (delta 0), pack-reused 959
Receiving objects: 100% (959/959), 703.93 KiB | 20.00 KiB/s, done.
Resolving deltas: 100% (468/468), done.

root@nanopineoplus2:/usr/RPi.GPIO_NP# python  setup.py install
running install
running build
running build_py
creating build
creating build/lib.linux-aarch64-2.7
creating build/lib.linux-aarch64-2.7/RPi
copying RPi/__init__.py -> build/lib.linux-aarch64-2.7/RPi
creating build/lib.linux-aarch64-2.7/RPi/GPIO
copying RPi/GPIO/__init__.py -> build/lib.linux-aarch64-2.7/RPi/GPIO
running build_ext
building 'RPi._GPIO' extension
creating build/temp.linux-aarch64-2.7
creating build/temp.linux-aarch64-2.7/source
aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-QCkEc0/python2.7-2.7.16=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c source/py_gpio.c -o build/temp.linux-aarch64-2.7/source/py_gpio.o
source/py_gpio.c: In function 'init_GPIO':
source/py_gpio.c:1034:16: warning: assignment to 'const int (*)[41]' from incompatible pointer type 'const int (*)[64]' [-Wincompatible-pointer-types]
    pin_to_gpio = &pin_to_gpio_nanopi;
                ^
aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-QCkEc0/python2.7-2.7.16=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c source/c_gpio.c -o build/temp.linux-aarch64-2.7/source/c_gpio.o
aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-QCkEc0/python2.7-2.7.16=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c source/cpuinfo.c -o build/temp.linux-aarch64-2.7/source/cpuinfo.o
source/cpuinfo.c: In function 'get_rpi_info':
source/cpuinfo.c:41:7: warning: ignoring return value of 'fgets', declared with attribute warn_unused_result [-Wunused-result]
       fgets(buffer, sizeof(buffer), fp);
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-QCkEc0/python2.7-2.7.16=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c source/event_gpio.c -o build/temp.linux-aarch64-2.7/source/event_gpio.o
source/event_gpio.c: In function 'event_cleanup':
source/event_gpio.c:405:9: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
         if ((gpio == -666) || (g->gpio == gpio))
         ^~
source/event_gpio.c:407:13: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
             remove_edge_detect(g->gpio);
             ^~~~~~~~~~~~~~~~~~
source/event_gpio.c:411:9: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
         if (epfd_blocking != -1)
         ^~
source/event_gpio.c:413:13: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
             epfd_blocking = -1;
             ^~~~~~~~~~~~~
source/event_gpio.c:414:9: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
         if (epfd_thread != -1)
         ^~
source/event_gpio.c:416:13: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
             epfd_thread = -1;
             ^~~~~~~~~~~
source/event_gpio.c: In function 'gpio_export':
source/event_gpio.c:64:5: warning: ignoring return value of 'write', declared with attribute warn_unused_result [-Wunused-result]
     write(fd, str_gpio, len);
     ^~~~~~~~~~~~~~~~~~~~~~~~
source/event_gpio.c: In function 'gpio_unexport':
source/event_gpio.c:79:5: warning: ignoring return value of 'write', declared with attribute warn_unused_result [-Wunused-result]
     write(fd, str_gpio, len);
     ^~~~~~~~~~~~~~~~~~~~~~~~
source/event_gpio.c: In function 'gpio_set_direction':
source/event_gpio.c:106:9: warning: ignoring return value of 'write', declared with attribute warn_unused_result [-Wunused-result]
         write(fd, "in", 3);
         ^~~~~~~~~~~~~~~~~~
source/event_gpio.c:108:9: warning: ignoring return value of 'write', declared with attribute warn_unused_result [-Wunused-result]
         write(fd, "out", 4);
         ^~~~~~~~~~~~~~~~~~~
source/event_gpio.c: In function 'gpio_set_edge':
source/event_gpio.c:124:5: warning: ignoring return value of 'write', declared with attribute warn_unused_result [-Wunused-result]
     write(fd, stredge[edge], strlen(stredge[edge]) + 1);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-QCkEc0/python2.7-2.7.16=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c source/soft_pwm.c -o build/temp.linux-aarch64-2.7/source/soft_pwm.o
aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-QCkEc0/python2.7-2.7.16=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c source/py_pwm.c -o build/temp.linux-aarch64-2.7/source/py_pwm.o
aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-QCkEc0/python2.7-2.7.16=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c source/common.c -o build/temp.linux-aarch64-2.7/source/common.o
aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-QCkEc0/python2.7-2.7.16=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c source/constants.c -o build/temp.linux-aarch64-2.7/source/constants.o
aarch64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-QCkEc0/python2.7-2.7.16=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-QCkEc0/python2.7-2.7.16=. -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-aarch64-2.7/source/py_gpio.o build/temp.linux-aarch64-2.7/source/c_gpio.o build/temp.linux-aarch64-2.7/source/cpuinfo.o build/temp.linux-aarch64-2.7/source/event_gpio.o build/temp.linux-aarch64-2.7/source/soft_pwm.o build/temp.linux-aarch64-2.7/source/py_pwm.o build/temp.linux-aarch64-2.7/source/common.o build/temp.linux-aarch64-2.7/source/constants.o -o build/lib.linux-aarch64-2.7/RPi/_GPIO.so
running install_lib
copying build/lib.linux-aarch64-2.7/RPi/_GPIO.so -> /usr/local/lib/python2.7/dist-packages/RPi
copying build/lib.linux-aarch64-2.7/RPi/GPIO/__init__.py -> /usr/local/lib/python2.7/dist-packages/RPi/GPIO
copying build/lib.linux-aarch64-2.7/RPi/__init__.py -> /usr/local/lib/python2.7/dist-packages/RPi
byte-compiling /usr/local/lib/python2.7/dist-packages/RPi/GPIO/__init__.py to __init__.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/RPi/__init__.py to __init__.pyc
running install_egg_info
Removing /usr/local/lib/python2.7/dist-packages/RPi.GPIO-0.6.3.egg-info
Writing /usr/local/lib/python2.7/dist-packages/RPi.GPIO-0.6.3.egg-info


root@nanopineoplus2:/usr/RPi.GPIO_NP# python
Python 2.7.16 (default, Oct 10 2019, 22:02:15)
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import RPi.GPIO
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "RPi/GPIO/__init__.py", line 23, in <module>
    from RPi._GPIO import *
ImportError: No module named _GPIO
>>> import RPi._GPIO
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named _GPIO
