### ISSUE TITLE
Error in fresh install

### ISSUE THREAD

**Issue by Ataraxiall** [auto3000/RPi.GPIO_NP#8]
Hi! 
im triying to install the library but i have this error

`/usr/include/python3.9/ceval.h:130:37: note: declared here
  130 | Py_DEPRECATED(3.9) PyAPI_FUNC(void) PyEval_InitThreads(void);
      |                                     ^~~~~~~~~~~~~~~~~~
arm-linux-gnueabihf-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-9BkwDf/python3.9-3.9.5=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-9BkwDf/python3.9-3.9.5=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.9 -c source/py_pwm.c -o build/temp.linux-armv7l-3.9/source/py_pwm.o
arm-linux-gnueabihf-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-9BkwDf/python3.9-3.9.5=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-9BkwDf/python3.9-3.9.5=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.9 -c source/soft_pwm.c -o build/temp.linux-armv7l-3.9/source/soft_pwm.o
arm-linux-gnueabihf-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-9BkwDf/python3.9-3.9.5=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-armv7l-3.9/source/c_gpio.o build/temp.linux-armv7l-3.9/source/common.o build/temp.linux-armv7l-3.9/source/constants.o build/temp.linux-armv7l-3.9/source/cpuinfo.o build/temp.linux-armv7l-3.9/source/event_gpio.o build/temp.linux-armv7l-3.9/source/py_gpio.o build/temp.linux-armv7l-3.9/source/py_pwm.o build/temp.linux-armv7l-3.9/source/soft_pwm.o -o build/lib.linux-armv7l-3.9/RPi/_GPIO.cpython-39-arm-linux-gnueabihf.so
/usr/bin/ld: build/temp.linux-armv7l-3.9/source/constants.o:/root/gits/RPi.GPIO_NP/source/common.h:42: multiple definition of `module_setup'; build/temp.linux-armv7l-3.9/source/common.o:/root/gits/RPi.GPIO_NP/source/common.h:42: first defined here
/usr/bin/ld: build/temp.linux-armv7l-3.9/source/constants.o:/root/gits/RPi.GPIO_NP/source/common.h:41: multiple definition of `setup_error'; build/temp.linux-armv7l-3.9/source/common.o:/root/gits/RPi.GPIO_NP/source/common.h:41: first defined here
/usr/bin/ld: build/temp.linux-armv7l-3.9/source/constants.o:/root/gits/RPi.GPIO_NP/source/common.h:40: multiple definition of `rpiinfo'; build/temp.linux-armv7l-3.9/source/common.o:/root/gits/RPi.GPIO_NP/source/common.h:40: first defined here
/usr/bin/ld: build/temp.linux-armv7l-3.9/source/constants.o:/root/gits/RPi.GPIO_NP/source/common.h:39: multiple definition of `gpio_direction'; build/temp.linux-armv7l-3.9/source/common.o:/root/gits/RPi.GPIO_NP/source/common.h:39: first defined here
/usr/bin/ld: build/temp.linux-armv7l-3.9/source/constants.o:/root/gits/RPi.GPIO_NP/source/common.h:38: multiple definition of `pin_to_gpio'; build/temp.linux-armv7l-3.9/source/common.o:/root/gits/RPi.GPIO_NP/source/common.h:38: first defined here
/usr/bin/ld: build/temp.linux-armv7l-3.9/source/constants.o:/root/gits/RPi.GPIO_NP/source/common.h:37: multiple definition of `pin_to_gpio_nanopi'; build/temp.linux-armv7l-3.9/source/common.o:/root/gits/RPi.GPIO_NP/source/common.h:37: first defined here
/usr/bin/ld: build/temp.linux-armv7l-3.9/source/constants.o:/root/gits/RPi.GPIO_NP/source/common.h:36: multiple definition of `pin_to_gpio_rev3'; build/temp.linux-armv7l-3.9/source/common.o:/root/gits/RPi.GPIO_NP/source/common.h:36: first defined here
/usr/bin/ld: build/temp.linux-armv7l-3.9/source/constants.o:/root/gits/RPi.GPIO_NP/source/common.h:35: multiple definition of `pin_to_gpio_rev2'; build/temp.linux-armv7l-3.9/source/common.o:/root/gits/RPi.GPIO_NP/source/common.h:35: first defined here
/usr/bin/ld: build/temp.linux-armv7l-3.9/source/constants.o:/root/gits/RPi.GPIO_NP/source/common.h:34: multiple definition of `pin_to_gpio_rev1'; build/temp.linux-armv7l-3.9/source/common.o:/root/gits/RPi.GPIO_NP/source/common.h:34: first defined here
/usr/bin/ld: build/temp.linux-armv7l-3.9/source/constants.o:/root/gits/RPi.GPIO_NP/source/common.h:33: multiple definition of `gpio_mode'; build/temp.linux-armv7l-3.9/source/common.o:/root/gits/RPi.GPIO_NP/source/common.h:33: first defined here
/usr/bin/ld: build/temp.linux-armv7l-3.9/source/py_gpio.o:/root/gits/RPi.GPIO_NP/source/common.h:33: multiple definition of `gpio_mode'; build/temp.linux-armv7l-3.9/source/common.o:/root/gits/RPi.GPIO_NP/source/common.h:33: first defined here
/usr/bin/ld: build/temp.linux-armv7l-3.9/source/py_gpio.o:/root/gits/RPi.GPIO_NP/source/common.h:41: multiple definition of `setup_error'; build/temp.linux-armv7l-3.9/source/common.o:/root/gits/RPi.GPIO_NP/source/common.h:41: first defined here
/usr/bin/ld: build/temp.linux-armv7l-3.9/source/py_gpio.o:/root/gits/RPi.GPIO_NP/source/common.h:40: multiple definition of `rpiinfo'; build/temp.linux-armv7l-3.9/source/common.o:/root/gits/RPi.GPIO_NP/source/common.h:40: first defined here
/usr/bin/ld: build/temp.linux-armv7l-3.9/source/py_gpio.o:/root/gits/RPi.GPIO_NP/source/common.h:39: multiple definition of `gpio_direction'; build/temp.linux-armv7l-3.9/source/common.o:/root/gits/RPi.GPIO_NP/source/common.h:39: first defined here
/usr/bin/ld: build/temp.linux-armv7l-3.9/source/py_gpio.o:/root/gits/RPi.GPIO_NP/source/common.h:42: multiple definition of `module_setup'; build/temp.linux-armv7l-3.9/source/common.o:/root/gits/RPi.GPIO_NP/source/common.h:42: first defined here
/usr/bin/ld: build/temp.linux-armv7l-3.9/source/py_gpio.o:/root/gits/RPi.GPIO_NP/source/common.h:38: multiple definition of `pin_to_gpio'; build/temp.linux-armv7l-3.9/source/common.o:/root/gits/RPi.GPIO_NP/source/common.h:38: first defined here
/usr/bin/ld: build/temp.linux-armv7l-3.9/source/py_gpio.o:/root/gits/RPi.GPIO_NP/source/common.h:37: multiple definition of `pin_to_gpio_nanopi'; build/temp.linux-armv7l-3.9/source/common.o:/root/gits/RPi.GPIO_NP/source/common.h:37: first defined here
/usr/bin/ld: build/temp.linux-armv7l-3.9/source/py_gpio.o:/root/gits/RPi.GPIO_NP/source/common.h:36: multiple definition of `pin_to_gpio_rev3'; build/temp.linux-armv7l-3.9/source/common.o:/root/gits/RPi.GPIO_NP/source/common.h:36: first defined here
/usr/bin/ld: build/temp.linux-armv7l-3.9/source/py_gpio.o:/root/gits/RPi.GPIO_NP/source/common.h:35: multiple definition of `pin_to_gpio_rev2'; build/temp.linux-armv7l-3.9/source/common.o:/root/gits/RPi.GPIO_NP/source/common.h:35: first defined here
/usr/bin/ld: build/temp.linux-armv7l-3.9/source/py_gpio.o:/root/gits/RPi.GPIO_NP/source/common.h:34: multiple definition of `pin_to_gpio_rev1'; build/temp.linux-armv7l-3.9/source/common.o:/root/gits/RPi.GPIO_NP/source/common.h:34: first defined here
/usr/bin/ld: build/temp.linux-armv7l-3.9/source/py_gpio.o:/root/gits/RPi.GPIO_NP/source/constants.h:42: multiple definition of `both_edge'; build/temp.linux-armv7l-3.9/source/constants.o:/root/gits/RPi.GPIO_NP/source/constants.h:42: first defined here
/usr/bin/ld: build/temp.linux-armv7l-3.9/source/py_gpio.o:/root/gits/RPi.GPIO_NP/source/constants.h:41: multiple definition of `falling_edge'; build/temp.linux-armv7l-3.9/source/constants.o:/root/gits/RPi.GPIO_NP/source/constants.h:41: first defined here
/usr/bin/ld: build/temp.linux-armv7l-3.9/source/py_gpio.o:/root/gits/RPi.GPIO_NP/source/constants.h:40: multiple definition of `rising_edge'; build/temp.linux-armv7l-3.9/source/constants.o:/root/gits/RPi.GPIO_NP/source/constants.h:40: first defined here
/usr/bin/ld: build/temp.linux-armv7l-3.9/source/py_gpio.o:/root/gits/RPi.GPIO_NP/source/constants.h:39: multiple definition of `pud_down'; build/temp.linux-armv7l-3.9/source/constants.o:/root/gits/RPi.GPIO_NP/source/constants.h:39: first defined here
/usr/bin/ld: build/temp.linux-armv7l-3.9/source/py_gpio.o:/root/gits/RPi.GPIO_NP/source/constants.h:38: multiple definition of `pud_up'; build/temp.linux-armv7l-3.9/source/constants.o:/root/gits/RPi.GPIO_NP/source/constants.h:38: first defined here
/usr/bin/ld: build/temp.linux-armv7l-3.9/source/py_gpio.o:/root/gits/RPi.GPIO_NP/source/constants.h:37: multiple definition of `pud_off'; build/temp.linux-armv7l-3.9/source/constants.o:/root/gits/RPi.GPIO_NP/source/constants.h:37: first defined here
/usr/bin/ld: build/temp.linux-armv7l-3.9/source/py_gpio.o:/root/gits/RPi.GPIO_NP/source/constants.h:36: multiple definition of `bcm'; build/temp.linux-armv7l-3.9/source/constants.o:/root/gits/RPi.GPIO_NP/source/constants.h:36: first defined here
/usr/bin/ld: build/temp.linux-armv7l-3.9/source/py_gpio.o:/root/gits/RPi.GPIO_NP/source/constants.h:35: multiple definition of `board'; build/temp.linux-armv7l-3.9/source/constants.o:/root/gits/RPi.GPIO_NP/source/constants.h:35: first defined here
/usr/bin/ld: build/temp.linux-armv7l-3.9/source/py_gpio.o:/root/gits/RPi.GPIO_NP/source/constants.h:34: multiple definition of `unknown'; build/temp.linux-armv7l-3.9/source/constants.o:/root/gits/RPi.GPIO_NP/source/constants.h:34: first defined here
/usr/bin/ld: build/temp.linux-armv7l-3.9/source/py_gpio.o:/root/gits/RPi.GPIO_NP/source/constants.h:33: multiple definition of `spi'; build/temp.linux-armv7l-3.9/source/constants.o:/root/gits/RPi.GPIO_NP/source/constants.h:33: first defined here
/usr/bin/ld: build/temp.linux-armv7l-3.9/source/py_gpio.o:/root/gits/RPi.GPIO_NP/source/constants.h:32: multiple definition of `i2c'; build/temp.linux-armv7l-3.9/source/constants.o:/root/gits/RPi.GPIO_NP/source/constants.h:32: first defined here
/usr/bin/ld: build/temp.linux-armv7l-3.9/source/py_gpio.o:/root/gits/RPi.GPIO_NP/source/constants.h:31: multiple definition of `serial'; build/temp.linux-armv7l-3.9/source/constants.o:/root/gits/RPi.GPIO_NP/source/constants.h:31: first defined here
/usr/bin/ld: build/temp.linux-armv7l-3.9/source/py_gpio.o:/root/gits/RPi.GPIO_NP/source/constants.h:30: multiple definition of `pwm'; build/temp.linux-armv7l-3.9/source/constants.o:/root/gits/RPi.GPIO_NP/source/constants.h:30: first defined here
/usr/bin/ld: build/temp.linux-armv7l-3.9/source/py_gpio.o:/root/gits/RPi.GPIO_NP/source/constants.h:29: multiple definition of `output'; build/temp.linux-armv7l-3.9/source/constants.o:/root/gits/RPi.GPIO_NP/source/constants.h:29: first defined here
/usr/bin/ld: build/temp.linux-armv7l-3.9/source/py_gpio.o:/root/gits/RPi.GPIO_NP/source/constants.h:28: multiple definition of `input'; build/temp.linux-armv7l-3.9/source/constants.o:/root/gits/RPi.GPIO_NP/source/constants.h:28: first defined here
/usr/bin/ld: build/temp.linux-armv7l-3.9/source/py_gpio.o:/root/gits/RPi.GPIO_NP/source/constants.h:27: multiple definition of `low'; build/temp.linux-armv7l-3.9/source/constants.o:/root/gits/RPi.GPIO_NP/source/constants.h:27: first defined here
/usr/bin/ld: build/temp.linux-armv7l-3.9/source/py_gpio.o:/root/gits/RPi.GPIO_NP/source/constants.h:26: multiple definition of `high'; build/temp.linux-armv7l-3.9/source/constants.o:/root/gits/RPi.GPIO_NP/source/constants.h:26: first defined here
/usr/bin/ld: build/temp.linux-armv7l-3.9/source/py_pwm.o:/root/gits/RPi.GPIO_NP/source/common.h:39: multiple definition of `gpio_direction'; build/temp.linux-armv7l-3.9/source/common.o:/root/gits/RPi.GPIO_NP/source/common.h:39: first defined here
/usr/bin/ld: build/temp.linux-armv7l-3.9/source/py_pwm.o:/root/gits/RPi.GPIO_NP/source/py_pwm.h:23: multiple definition of `PWMType'; build/temp.linux-armv7l-3.9/source/py_gpio.o:/root/gits/RPi.GPIO_NP/source/py_pwm.h:23: first defined here
/usr/bin/ld: build/temp.linux-armv7l-3.9/source/py_pwm.o:/root/gits/RPi.GPIO_NP/source/common.h:42: multiple definition of `module_setup'; build/temp.linux-armv7l-3.9/source/common.o:/root/gits/RPi.GPIO_NP/source/common.h:42: first defined here
/usr/bin/ld: build/temp.linux-armv7l-3.9/source/py_pwm.o:/root/gits/RPi.GPIO_NP/source/common.h:41: multiple definition of `setup_error'; build/temp.linux-armv7l-3.9/source/common.o:/root/gits/RPi.GPIO_NP/source/common.h:41: first defined here
/usr/bin/ld: build/temp.linux-armv7l-3.9/source/py_pwm.o:/root/gits/RPi.GPIO_NP/source/common.h:40: multiple definition of `rpiinfo'; build/temp.linux-armv7l-3.9/source/common.o:/root/gits/RPi.GPIO_NP/source/common.h:40: first defined here
/usr/bin/ld: build/temp.linux-armv7l-3.9/source/py_pwm.o:/root/gits/RPi.GPIO_NP/source/common.h:38: multiple definition of `pin_to_gpio'; build/temp.linux-armv7l-3.9/source/common.o:/root/gits/RPi.GPIO_NP/source/common.h:38: first defined here
/usr/bin/ld: build/temp.linux-armv7l-3.9/source/py_pwm.o:/root/gits/RPi.GPIO_NP/source/common.h:37: multiple definition of `pin_to_gpio_nanopi'; build/temp.linux-armv7l-3.9/source/common.o:/root/gits/RPi.GPIO_NP/source/common.h:37: first defined here
/usr/bin/ld: build/temp.linux-armv7l-3.9/source/py_pwm.o:/root/gits/RPi.GPIO_NP/source/common.h:36: multiple definition of `pin_to_gpio_rev3'; build/temp.linux-armv7l-3.9/source/common.o:/root/gits/RPi.GPIO_NP/source/common.h:36: first defined here
/usr/bin/ld: build/temp.linux-armv7l-3.9/source/py_pwm.o:/root/gits/RPi.GPIO_NP/source/common.h:35: multiple definition of `pin_to_gpio_rev2'; build/temp.linux-armv7l-3.9/source/common.o:/root/gits/RPi.GPIO_NP/source/common.h:35: first defined here
/usr/bin/ld: build/temp.linux-armv7l-3.9/source/py_pwm.o:/root/gits/RPi.GPIO_NP/source/common.h:34: multiple definition of `pin_to_gpio_rev1'; build/temp.linux-armv7l-3.9/source/common.o:/root/gits/RPi.GPIO_NP/source/common.h:34: first defined here
/usr/bin/ld: build/temp.linux-armv7l-3.9/source/py_pwm.o:/root/gits/RPi.GPIO_NP/source/common.h:33: multiple definition of `gpio_mode'; build/temp.linux-armv7l-3.9/source/common.o:/root/gits/RPi.GPIO_NP/source/common.h:33: first defined here
/usr/bin/ld: build/temp.linux-armv7l-3.9/source/soft_pwm.o:/root/gits/RPi.GPIO_NP/source/soft_pwm.c:28: multiple definition of `threads'; build/temp.linux-armv7l-3.9/source/event_gpio.o:/root/gits/RPi.GPIO_NP/source/event_gpio.c:48: first defined here
collect2: error: ld returned 1 exit status
error: command '/usr/bin/arm-linux-gnueabihf-gcc' failed with exit code 1`

Any idea?

Thanks!

**Comment by auto3000** [comment]
Hello @Ataraxiall, at first glance I can see python version 3.9 (and I think I'm using python 3.6). Moreover we can see a suspicious warning "Py_DEPRECATED"...

What is your environment ? Ubuntu 2x.xx ?

**Comment by Ataraxiall** [comment]
Thanks for you fast response.

Im using Armbian bullseye (21.08.1) in a nanopi neo core.
Python 3.9.5
Its posible that can be Python version?

I dont know if i can do downgrade

Thanks!

**Comment by auto3000** [comment]
@Ataraxiall  I cannot fix by myself quickly (because I have to replicate your environment) but I could suggest a correction.

When looking to error log, it looks this problem is due to the version of "gcc" instead, which is quite new version (which is good, we all like recent gcc). But this code does not comply with recent new gcc behavior.

Please have look to the common.h below:
![image](https://user-images.githubusercontent.com/8845975/139864115-1fdedd7f-d8c9-4280-b379-bfc1d2856d75.png)

The global variables are declared without "extern ...". Could try to modify  any global variables like "int gpio_mode;" to "extern int gpio_mode;" in common.h. This same modification could apply to 39-42.

**Comment by auto3000** [comment]
@Ataraxiall I finally suspect you do not need to change your version of Python... this would work. For info, the warning about deprecated procedure is just a message to mention we could simply remove this code soon.

![image](https://user-images.githubusercontent.com/8845975/139865199-3acbb630-aef5-462b-9f1d-939117b5e3ff.png)

I think the code will work the same without lines 1049-1050 at:
![image](https://user-images.githubusercontent.com/8845975/139865363-1cb46331-a8b8-49eb-a237-9d92ec917a92.png)

**Comment by Ataraxiall** [comment]
> @Ataraxiall No puedo arreglarlo solo rápidamente (porque tengo que replicar su entorno) pero podría sugerir una corrección.
> 
> Al mirar el registro de errores, parece que este problema se debe a la versión de "gcc", que es una versión bastante nueva (lo cual es bueno, a todos nos gusta la reciente gcc). Pero este código no cumple con el nuevo comportamiento reciente de gcc.
> 
> Por favor, consulte el archivo common.h a continuación: ![imagen](https://user-images.githubusercontent.com/8845975/139864115-1fdedd7f-d8c9-4280-b379-bfc1d2856d75.png)
> 
> Las variables globales se declaran sin "extern ...". Podría intentar modificar cualquier variable global como "int gpio_mode;" a "extern int gpio_mode;" en común h. Esta misma modificación podría aplicarse a 39-42.
I try but same result  :(
![image](https://user-images.githubusercontent.com/67580921/139867335-8d86fcad-0f2e-4e04-a5a3-8a8cee27de13.png)

What version of gcc should work?

Thanks

**Comment by auto3000** [comment]
I'm using gcc 9.2.0... 

It looks we should use also "extern" on "const" variables too. Could you provide the new error log (to check if the first modification set is making progress...)

**Comment by Ataraxiall** [comment]
I tried to change all where the line gave an error, it seemed that it installed well, but then the python library was not accessible.

I have installed python3.7 from sources and changed the default version of the compiler (I have used this guide but with version 9 https://linuxconfig.org/how-to-switch-between-multiple-gcc-and-g- compiler-versions-on-ubuntu-20-04-lts-focal-fossa) and everything went well without failures.

Thank you very much anyway for your help :)

**Comment by auto3000** [comment]
@Ataraxiall good to know thanks.

Do not hesitate to submit your code changes (through a merge request in github), this could help someone else in future.

**Comment by Ataraxiall** [comment]
I created a pull request.
I am very very new to github, if I have done it wrong, forgive me please.
no need to downgrade python, just putting this in and making sure you have GCC-9 and G ++ - 9 works.

`import os
os.environ["CC"] = "gcc-9"
os.environ["CXX"] = "g++-9"`

Cheers
